version: '3'
services:
  web:
    build: ./backend
    ports:
      - '8080:8080'
    container_name: backend-node-container

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    container_name: frontend-react-container
